// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqjqffsupbeguhnuthsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxanFmZnN1cGJlZ3VobnV0aHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDM0MjYsImV4cCI6MjA2MDExOTQyNn0.jj7BI5PS1RZ5ZA8apbHqIFB3LfjRGX6ihfFJm18thmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);